# -*- coding: utf-8 -*-
"""graficas_Morelosipynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VSpN9PL7Z4seBtORsZIVUan8QtS0_b4m
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Datos extraídos del "Anexo A" del reporte (Utilidad Neta en MXN)
data = [
    {"Año": 2018, "Cultivo": "Maíz grano", "Utilidad Neta (MXN)": 691473.25 + 8474720.95}, # Suma de los dos registros de 2018
    {"Año": 2018, "Cultivo": "Sorgo grano", "Utilidad Neta (MXN)": 6861476.94},
    {"Año": 2019, "Cultivo": "Maíz grano", "Utilidad Neta (MXN)": 4353486.42},
    {"Año": 2019, "Cultivo": "Sorgo grano", "Utilidad Neta (MXN)": 10576976.66},
    {"Año": 2020, "Cultivo": "Maíz grano", "Utilidad Neta (MXN)": 5093593.50},
    {"Año": 2021, "Cultivo": "Maíz grano", "Utilidad Neta (MXN)": 5586353.61},
    {"Año": 2021, "Cultivo": "Sorgo grano", "Utilidad Neta (MXN)": 8045391.60},
    {"Año": 2022, "Cultivo": "Maíz grano", "Utilidad Neta (MXN)": 12230134.62},
    {"Año": 2022, "Cultivo": "Sorgo grano", "Utilidad Neta (MXN)": 10309287.61},
    {"Año": 2023, "Cultivo": "Maíz grano", "Utilidad Neta (MXN)": 5242921.24},
    {"Año": 2024, "Cultivo": "Maíz grano", "Utilidad Neta (MXN)": 13082189.87},
    # Proyecciones 2025
    {"Año": 2025, "Cultivo": "Maíz grano", "Utilidad Neta (MXN)": -7087.85},
    {"Año": 2025, "Cultivo": "Higo", "Utilidad Neta (MXN)": 436655.16},
    {"Año": 2025, "Cultivo": "Caña de azúcar", "Utilidad Neta (MXN)": 622055.02},
    {"Año": 2025, "Cultivo": "Sorgo grano", "Utilidad Neta (MXN)": -7876.53},
    {"Año": 2025, "Cultivo": "Lechuga (NFT)", "Utilidad Neta (MXN)": 121574.98},
    # Proyecciones 2026
    {"Año": 2026, "Cultivo": "Maíz grano", "Utilidad Neta (MXN)": -7193.23},
    {"Año": 2026, "Cultivo": "Higo", "Utilidad Neta (MXN)": 437337.17},
    {"Año": 2026, "Cultivo": "Caña de azúcar", "Utilidad Neta (MXN)": 622627.83},
    {"Año": 2026, "Cultivo": "Sorgo grano", "Utilidad Neta (MXN)": -7909.87},
    {"Año": 2026, "Cultivo": "Lechuga (NFT)", "Utilidad Neta (MXN)": 121722.34}
]

# 2. Crear el DataFrame de Pandas
df = pd.DataFrame(data)

# 3. Configuración de la gráfica
plt.figure(figsize=(14, 7))
sns.set_theme(style="whitegrid")

# Crear un gráfico de barras agrupado por Año y coloreado por Cultivo
ax = sns.barplot(
    data=df,
    x="Año",
    y="Utilidad Neta (MXN)",
    hue="Cultivo",
    palette="tab10"
)

# 4. Personalización del diseño
plt.title('Histórico y Proyección de Utilidad Neta por Cultivo (2018-2026)', fontsize=16, fontweight='bold')
plt.xlabel('Año', fontsize=12)
plt.ylabel('Utilidad Neta (Pesos MXN)', fontsize=12)
plt.axhline(0, color='red', linestyle='--', linewidth=1.5) # Línea de cero para resaltar pérdidas
plt.legend(title='Cultivo', bbox_to_anchor=(1.05, 1), loc='upper left')

# Formatear el eje Y para mostrar valores monetarios
ylabels = ['${:,.0f}'.format(y) for y in ax.get_yticks()]
ax.set_yticklabels(ylabels)

# Mostrar la gráfica
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Datos extraídos del "Anexo A" del reporte de Cuautla (Utilidad Neta en MXN)
data = [
    # Datos Históricos (2018-2024)
    {"Año": 2018, "Cultivo": "Maíz grano", "Utilidad Neta (MXN)": 12600592.98},
    {"Año": 2018, "Cultivo": "Sorgo grano", "Utilidad Neta (MXN)": 32040998.30},
    {"Año": 2018, "Cultivo": "Caña de azúcar", "Utilidad Neta (MXN)": 144652158.22},
    {"Año": 2018, "Cultivo": "Higo", "Utilidad Neta (MXN)": 5856396.44},

    {"Año": 2019, "Cultivo": "Maíz grano", "Utilidad Neta (MXN)": 14132837.48},
    {"Año": 2019, "Cultivo": "Sorgo grano", "Utilidad Neta (MXN)": 38076102.41},
    {"Año": 2019, "Cultivo": "Higo", "Utilidad Neta (MXN)": 5971650.00},

    {"Año": 2020, "Cultivo": "Maíz grano", "Utilidad Neta (MXN)": 14297494.09},
    {"Año": 2020, "Cultivo": "Sorgo grano", "Utilidad Neta (MXN)": 39320350.68},

    {"Año": 2021, "Cultivo": "Maíz grano", "Utilidad Neta (MXN)": 15081542.20},

    {"Año": 2022, "Cultivo": "Maíz grano", "Utilidad Neta (MXN)": 23957997.02},
    {"Año": 2022, "Cultivo": "Sorgo grano", "Utilidad Neta (MXN)": 52121373.33},
    {"Año": 2022, "Cultivo": "Higo", "Utilidad Neta (MXN)": 5871109.76},

    {"Año": 2023, "Cultivo": "Maíz grano", "Utilidad Neta (MXN)": 13582858.74},
    {"Año": 2023, "Cultivo": "Sorgo grano", "Utilidad Neta (MXN)": 38155455.74},
    {"Año": 2023, "Cultivo": "Higo", "Utilidad Neta (MXN)": 5148893.83},

    {"Año": 2024, "Cultivo": "Maíz grano", "Utilidad Neta (MXN)": 10733064.66},
    {"Año": 2024, "Cultivo": "Sorgo grano", "Utilidad Neta (MXN)": 43452605.47},
    {"Año": 2024, "Cultivo": "Higo", "Utilidad Neta (MXN)": 6531435.79},

    # Proyecciones (2025)
    {"Año": 2025, "Cultivo": "Maíz grano", "Utilidad Neta (MXN)": -13410.61},
    {"Año": 2025, "Cultivo": "Higo", "Utilidad Neta (MXN)": 367782.89},
    {"Año": 2025, "Cultivo": "Caña de azúcar", "Utilidad Neta (MXN)": 529416.86},
    {"Año": 2025, "Cultivo": "Sorgo grano", "Utilidad Neta (MXN)": -15230.89},
    {"Año": 2025, "Cultivo": "Lechuga (NFT)", "Utilidad Neta (MXN)": 97693.88},

    # Proyecciones (2026)
    {"Año": 2026, "Cultivo": "Maíz grano", "Utilidad Neta (MXN)": -13263.71},
    {"Año": 2026, "Cultivo": "Higo", "Utilidad Neta (MXN)": 366832.79},
    {"Año": 2026, "Cultivo": "Caña de azúcar", "Utilidad Neta (MXN)": 529434.23},
    {"Año": 2026, "Cultivo": "Sorgo grano", "Utilidad Neta (MXN)": -15283.32},
    {"Año": 2026, "Cultivo": "Lechuga (NFT)", "Utilidad Neta (MXN)": 97809.75}
]

# 2. Crear el DataFrame de Pandas
df = pd.DataFrame(data)

# 3. Configuración de la gráfica
plt.figure(figsize=(14, 7))
sns.set_theme(style="whitegrid")

# Crear un gráfico de barras agrupado por Año y coloreado por Cultivo
ax = sns.barplot(
    data=df,
    x="Año",
    y="Utilidad Neta (MXN)",
    hue="Cultivo",
    palette="tab10"
)

# 4. Personalización del diseño
plt.title('Histórico y Proyección de Utilidad Neta por Cultivo en Cuautla (2018-2026)', fontsize=16, fontweight='bold')
plt.xlabel('Año', fontsize=12)
plt.ylabel('Utilidad Neta (Pesos MXN)', fontsize=12)
plt.axhline(0, color='red', linestyle='--', linewidth=1.5) # Línea de cero para resaltar pérdidas
plt.legend(title='Cultivo', bbox_to_anchor=(1.05, 1), loc='upper left')

# Formatear el eje Y para mostrar valores monetarios
from matplotlib.ticker import FixedLocator, FuncFormatter
current_ticks = ax.get_yticks()
ax.yaxis.set_major_locator(FixedLocator(current_ticks))
ax.yaxis.set_major_formatter(FuncFormatter(lambda y, p: '${:,.0f}'.format(y)))

# Mostrar la gráfica
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 1. Datos extraídos del "Anexo A" del reporte de Jiutepec (Utilidad Neta en MXN)
data = [
    # Histórico 2018
    {"Año": 2018, "Cultivo": "Maíz grano", "Utilidad Neta (MXN)": 763833.41},

    # Proyecciones 2025
    {"Año": 2025, "Cultivo": "Maíz grano", "Utilidad Neta (MXN)": -16014.43},
    {"Año": 2025, "Cultivo": "Higo", "Utilidad Neta (MXN)": 343016.02},
    {"Año": 2025, "Cultivo": "Caña de azúcar", "Utilidad Neta (MXN)": 497671.20},
    {"Año": 2025, "Cultivo": "Sorgo grano", "Utilidad Neta (MXN)": -18392.05},
    {"Año": 2025, "Cultivo": "Lechuga (NFT)", "Utilidad Neta (MXN)": 89077.28},

    # Proyecciones 2026
    {"Año": 2026, "Cultivo": "Maíz grano", "Utilidad Neta (MXN)": -15954.59},
    {"Año": 2026, "Cultivo": "Higo", "Utilidad Neta (MXN)": 342045.74},
    {"Año": 2026, "Cultivo": "Caña de azúcar", "Utilidad Neta (MXN)": 497817.24},
    {"Año": 2026, "Cultivo": "Sorgo grano", "Utilidad Neta (MXN)": -18478.38},
    {"Año": 2026, "Cultivo": "Lechuga (NFT)", "Utilidad Neta (MXN)": 89307.19}
]

# 2. Crear el DataFrame
df = pd.DataFrame(data)

# 3. Configuración de la gráfica
plt.figure(figsize=(12, 6))
sns.set_theme(style="whitegrid")

# Crear gráfica de barras
ax = sns.barplot(
    data=df,
    x="Año",
    y="Utilidad Neta (MXN)",
    hue="Cultivo",
    palette="magma"
)

# 4. Personalización del diseño
plt.title('Histórico y Proyección de Utilidad Neta por Cultivo - Jiutepec (2018-2026)', fontsize=15, fontweight='bold')
plt.xlabel('Año', fontsize=12)
plt.ylabel('Utilidad Neta (MXN)', fontsize=12)

# Añadir línea roja punteada en el 0 para evidenciar las pérdidas del maíz y sorgo
plt.axhline(0, color='red', linestyle='--', linewidth=1.5)

# Formatear el eje Y como moneda para facilitar la lectura
ylabels = ['${:,.0f}'.format(y) for y in ax.get_yticks()]
ax.set_yticklabels(ylabels)

# Ajustar la leyenda fuera del área de trazado
plt.legend(title='Cultivo', bbox_to_anchor=(1.02, 1), loc='upper left')

# Mostrar la gráfica
plt.tight_layout()
plt.show()